# Generated by Django 4.2.2 on 2023-06-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_owner_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_age',
            new_name='birth_date',
        ),
    ]
