# Generated by Django 4.2.2 on 2023-06-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_birth_age_profile_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_list', models.ManyToManyField(blank=True, to='profiles.profile')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='profiles.profile')),
            ],
        ),
    ]
