# Generated by Django 4.2.2 on 2023-06-19 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_blockedusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_list', models.ManyToManyField(blank=True, related_name='like_list', to='profiles.profile')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
