"""
Script for poulate db with tags for
testing and development purposes.
"""

def tags():
    from tags.models import Tags
    tags = [
            "Alternative",
            "Gothic",
            "Punk",
            "Metalhead",
            "Hippie",
            "Bohemian",
            "Tattoos",
            "Piercings",
            "Rockabilly",
            "Indie",
            "Hipster",
            "Skater",
            "Retro",
            "Rocker",
            "Electronic",
            "Art",
            "Experimental",
            "Eco-friendly",
            "Veganism",
            "Vegetarian",
            "Activism",
            "LGBTQ+",
            "Geek Culture",
            "Freak",
            "Traveler",
            "Minimalist",
            "Vintage",
            "Handmade",
            "Gastronomy",
            "Filmmaker",
            "Reader",
            "Photography",
            "Artist",
            "Designer",
            "Festivalgoer",
            "Concerts",
            "Electronic Music",
            "Classic Rock",
            "Hip-hop",
            "Reggae",
            "Ska",
            "Folk",
            "Psychedelic",
            "Grunge",
            "Alternative Pop",
            "Alternative Fashion",
            "Underground",
            "Cyberpunk",
            "Alternative Architecture",
            "Nature Lover",
            "Adventurer",
            "Fitness Enthusiast",
            "Sustainable Living",
            'Adventurous',
            'Animal Lover',
            'Artist',
            'Athlete',
            'Beach Lover',
            'Entrepreneur',
            'Book Lover',
            'Joker',
            'Coffee Lover',
            'Dancer',
            'Extreme Sports Enthusiast',
            'Foodie',
            'Gamer',
            'Traveler',
            'Geek',
            'Music Lover',
            'Spiritual',
            'Fitness Fanatic',
            'Environmental Activist',
            'Filmmaker',
            'Comedian',
            'Adventurous Cook',
            'Photography Lover',
            'Intellectual',
            'Yoga Lover',
            'Concert Goer',
            'Festival Lover',
            'Philanthropist',
            'Football Fan',
            'Fashion Lover',
            'Theater Lover',
            'Wine Enthusiast',
            'Car Lover',
            'Architect',
            'Barista',
            'Empathetic',
            'Gardening Lover',
            'Mountain Adventurer',
            'Landscape Photographer',
            'Community Leader',
            'Writer',
            'Dog Lover',
            'Basketball Fan',
            'Free Spirit',
            'Aspiring Musician',
            'Human Rights Advocate',
            'Video Game Enthusiast',
            'Technology Enthusiast'
    ]

    clean_list = list(set(tags))

    for item in clean_list:
        Tags.objects.create(tag_name=item)
